openapi: 3.0.1
info:
  title: Example API
  description: abc
  version: 1.0.0
externalDocs:
  description: GitHub link
  url: https://github.com/sashee/openapi_lambda
servers:
- url: ${api_url}
components:
  x-amazon-apigateway-integrations:
    users:
      type: aws_proxy
      uri: ${users_lambda_arn}
      httpMethod: POST
      passthroughBehavior: when_no_match
      contentHandling: CONVERT_TO_TEXT
      payloadFormatVersion: 2.0
    user:
      type: aws_proxy
      uri: ${user_lambda_arn}
      httpMethod: POST
      passthroughBehavior: when_no_match
      contentHandling: CONVERT_TO_TEXT
      payloadFormatVersion: 2.0
paths:
  /user:
    options:
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/users'
    get:
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/users'
      operationId: listUsers
      summary: List users
      responses:
        200:
          description: successful operation
    post:
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/users'
      operationId: createUser
      summary: Create user
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
              additionalProperties: false
        required: true
      responses:
        default:
          description: Success
  '/user/{userid}':
    parameters:
    - name: userid
      in: path
      required: true
      schema:
        type: string
    options:
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/user'
    get:
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/user'
      operationId: getUser
      summary: Return user  
      responses:
        200:
          description: Success
    put:
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/user'
      operationId: updateUser
      summary: Update user
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
              additionalProperties: false
        required: true
      responses:
        200:
          description: Success
    delete:
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/user'
      operationId: deleteUser
      summary: Delete user
      responses:
        200:
          description: Success
